// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function accumulate(f, x) {
  if (x) {
    return {
            hd: Curry._1(f, x.hd),
            tl: accumulate(f, x.tl)
          };
  } else {
    return /* [] */0;
  }
}

exports.accumulate = accumulate;
/* No side effect */
