// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");

function abbreviate(words) {
  var firsts = words.match(/\b(\w)/g);
  if (firsts !== null) {
    return $$String.uppercase_ascii(firsts.join(""));
  } else {
    return "";
  }
}

exports.abbreviate = abbreviate;
/* No side effect */
