// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function remainderOf(year, n) {
  return Caml_int32.mod_(year, n) === 0;
}

function isLeapYear(year) {
  if (remainderOf(year, 400) || !(remainderOf(year, 100) || !remainderOf(year, 4))) {
    return true;
  } else {
    return false;
  }
}

exports.remainderOf = remainderOf;
exports.isLeapYear = isLeapYear;
/* No side effect */
