// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function twoFer(name) {
  if (name !== undefined) {
    return "One for " + (name + ", one for me.");
  } else {
    return "One for you, one for me.";
  }
}

exports.twoFer = twoFer;
/* No side effect */
